### ISSUE TITLE
Add option to rednder on the left side of terminal

### ISSUE THREAD

**Issue by GRbit** [foxfriends/paper-terminal#10]
Sometimes I use quite wide terminal windows on 4k display, most of the thing are written on the left side of it, but when I use paper it automatically place rendered markdown in the center of my terminal window which isn't very convenient. It would be great to have an option for the renderer to write a paper without this center alignment

**Comment by foxfriends** [comment]
Added in version 3.0.0, both left (`-l` or `--left`) and right (`-r` or `--right`) have been added.

**Comment by GRbit** [comment]
Oh. Sorry for disturbing. I've just installed the program via cargo and -h didn't show this option.

Also, you made a great tool, I like it!

14 Nov 2023 22:24:05 Cameron Eldridge ***@***.***>:

**Comment by foxfriends** [comment]
Oh haha not disturbed at all! I built that feature just now for you.

It should be there, I just did a fresh `cargo install paper-terminal` and it is shown in the help now.

**Comment by GRbit** [comment]
> Oh haha not disturbed at all! I built that feature just now for you.

Many thanks to you!
I thought you were writing like "it's already available" :grin: 

I've just tested it, works like a charm :heart:
