### ISSUE TITLE
incorrect width calculation for chinese 

### ISSUE THREAD

**Issue by Alsan** [foxfriends/paper-terminal#6]
as the screenshot below:

![2022-05-15_08-02](https://user-images.githubusercontent.com/217947/168451887-6b921ef0-edb9-4888-97ae-efa73893b663.jpg)

**Comment by foxfriends** [comment]
Thanks, I will investigate soon

**Comment by foxfriends** [comment]
This should be fixed in version 2.2.0. I don't have great test cases for this though, let me know if you see any more issues!

**Comment by Alsan** [comment]
A lot better now, but still some edge case, see below:

- pic 1
![2022-06-23_07-51](https://user-images.githubusercontent.com/217947/175179538-ced0dbf0-22cb-4b19-9e19-eeaa3b1b24a4.jpg)

- pic 2
![2022-06-23_07-53](https://user-images.githubusercontent.com/217947/175179594-efe0a242-7cad-420a-a088-a6d6029e97bb.jpg)

**Comment by foxfriends** [comment]
Ok thank you I will look into those soon as well. Could you send me the text of one of those lines so I can test with it?

**Comment by Alsan** [comment]
Of cause, pls see the attachment below.

[notes.tar.gz](https://github.com/foxfriends/paper-terminal/files/8964612/notes.tar.gz)

**Comment by foxfriends** [comment]
Thank you for the notes, I have ensured all of those look good in version 2.2.1!

**Comment by Alsan** [comment]
It works perfectly for me, thank you.
