### ISSUE TITLE
Add an option for white text on black

### ISSUE THREAD

**Issue by elyashivhazan** [foxfriends/paper-terminal#9]
Hi, just saw this project and the format is the best. Will it be passable to implement a black page?

**Comment by foxfriends** [comment]
Yes it is possible to configure all the colours this uses by defining [stylesheet](https://github.com/foxfriends/paper-terminal#styling).

Refer to the documentation on [Syncat Themes](https://github.com/foxfriends/syncat-themes) for how to create and install those stylesheets.

You'll find the default stylesheet here: https://github.com/foxfriends/paper-terminal/blob/master/src/default.syncat

The last block defines the paper and base text colour:

```
paper {
  background-color: white;
  color: black;
}
```

You can swap those and it should be pretty close to white text on black paper:

```
paper {
  background-color: color;
  color: white;
}
```

Let me know if this all works

**Comment by elyashivhazan** [comment]
Hi, thanks for the reply.
I could not understand where should I create `paper.syncat` file.

**Comment by foxfriends** [comment]
Where you put it depends on the operating system:

Linux: `$HOME/.config/syncat/style/active`
Mac: `$HOME/Library/Preferences/com.cameldridge.syncat/style/active`

You can put the file in that folder. It should look like this folder: https://github.com/foxfriends/dotfiles/tree/main/syncat
